### ISSUE TITLE
Task :@react-native-async-storage_async-storage:extractDebugAnnotations FAILED

### ISSUE THREAD

**Issue by NiceLeader** [react-native-async-storage/async-storage#1142]
### What happened?

Hi guys i have an issue connected with react-native-async-storage_async, can someone help me with that? thanks in advance :)
"react": "18.2.0",
"react-native": "0.74.5",
distributionUrl=https\://services.gradle.org/distributions/gradle-8.9-bin.zip
classpath 'com.android.tools.build:gradle:8.5.0'

> Task :@react-native-async-storage_async-storage:extractDebugAnnotations FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':@react-native-async-storage_async-storage:extractDebugAnnotations'.
> Error while evaluating property 'hasAndroidAnnotations' of task ':@react-native-async-storage_async-storage:extractDebugAnnotations'.
   > Could not resolve all artifacts for configuration ':@react-native-async-storage_async-storage:debugCompileClasspath'.
      > Could not find any matches for com.facebook.react:react-native:+ as no versions of com.facebook.react:react-native are available.
        Required by:
            project :@react-native-async-storage_async-storage

* Try:

You can use '--warning-mode all' to show the individual deprecation warnings and determine if 
they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.9/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 2s
12 actionable tasks: 11 executed, 1 up-to-date

### Version

2.0.0

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\macie\AppData\Roaming\nvm\v18.20.4\node_modules\npm\bin\npm-cli.js
1 info using npm@10.7.0
2 info using node@v18.20.4
3 silly config:load:file:C:\Users\macie\AppData\Roaming\nvm\v18.20.4\node_modules\npm\npmrc
4 silly config:load:file:E:\nameofapp\.npmrc
5 silly config:load:file:C:\Users\macie\.npmrc
6 silly config:load:file:C:\Program Files\nodejs\etc\npmrc
7 verbose title npm exec react native info
8 verbose argv "exec" "--" "react" "native" "info"
9 verbose logfile logs-max:10 dir:C:\Users\macie\AppData\Local\npm-cache\_logs\2024-08-23T11_51_25_033Z-
10 verbose logfile C:\Users\macie\AppData\Local\npm-cache\_logs\2024-08-23T11_51_25_033Z-debug-0.log
11 silly logfile start cleaning logs, removing 1 files
12 silly logfile done cleaning log files
13 verbose stack Error: could not determine executable to run
13 verbose stack     at getBinFromManifest (C:\Users\macie\AppData\Roaming\nvm\v18.20.4\node_modules\npm\node_modules\libnpmexec\lib\get-bin-from-manifest.js:17:23)
13 verbose stack     at exec (C:\Users\macie\AppData\Roaming\nvm\v18.20.4\node_modules\npm\node_modules\libnpmexec\lib\index.js:183:15)
13 verbose stack     at async module.exports (C:\Users\macie\AppData\Roaming\nvm\v18.20.4\node_modules\npm\lib\cli\entry.js:74:5)
14 verbose pkgid react@18.2.0
15 verbose cwd E:\nameofapp
16 verbose Windows_NT 10.0.19045
17 verbose node v18.20.4
18 verbose npm  v10.7.0
19 error could not determine executable to run
20 verbose exit 1
21 verbose code 1
22 error A complete log of this run can be found in: C:\Users\macie\AppData\Local\npm-cache\_logs\2024-08-23T11_51_25_033Z-debug-0.log
```

### Steps to Reproduce

i type ./gradlew check and get this, any command for building also does this apk cannot be build

**Comment by AW0z** [comment]
Hi, I've got the same issue.

**Comment by NiceLeader** [comment]
Anyone?

**Comment by NiceLeader** [comment]
Hey, @mensonones 
I have solved this issue; however, a new problem has arisen that isn't necessarily related to this library. 

FAILURE: Build failed with an exception.

* What went wrong:
Cannot locate tasks that match 'app:installDevDebug' as task 
'installDevDebug' not found in project ':app'.

**Comment by mensonones** [comment]
> Hey, @mensonones I have solved this issue; however, a new problem has arisen that isn't necessarily related to this library.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Cannot locate tasks that match 'app:installDevDebug' as task
>   'installDevDebug' not found in project ':app'.

Oh, Great! If you don't have any more problems related to the library, you can close the issue. 
If you still have problems related to the library, I will try to help you. :)

**Comment by yyyyyyyysssss** [comment]
> 嘿，@mensonones 我已经解决了这个问题；然而，又出现了一个新问题，它不一定与这个库有关。
> 
> 失败：构建因异常而失败。
> 
> * 出了什么问题：
>   无法找到与“app：installDevDebug”匹配的任务，因为
>   在项目“：app”中未找到任务“installDevDebug”。

How do I solve this problem now
