### ISSUE TITLE
Detox 12 not compatible with XCode 12, please upgrade detox

### ISSUE THREAD

**Issue by djhr** [react-native-async-storage/async-storage#454]
## Current behavior

Yarn fails to install with the following error:

```
error /Users/djhr/Library/Caches/Yarn/v6/.tmp/08757a422460db4f0967139a62ebf40c.2f95ec27a6e0e1a87682fbb817b25f2f9d80531f.prepare/node_modules/detox: Command failed.
Exit code: 1
Command: node scripts/postinstall.js
Arguments: 
Directory: /Users/djhr/Library/Caches/Yarn/v6/.tmp/08757a422460db4f0967139a62ebf40c.2f95ec27a6e0e1a87682fbb817b25f2f9d80531f.prepare/node_modules/detox
Output:
+ xcodebuild -version
+++ dirname /Users/djhr/Library/Caches/Yarn/v6/.tmp/08757a422460db4f0967139a62ebf40c.2f95ec27a6e0e1a87682fbb817b25f2f9d80531f.prepare/node_modules/detox/scripts/build_framework.ios.sh
++ dirname /Users/djhr/Library/Caches/Yarn/v6/.tmp/08757a422460db4f0967139a62ebf40c.2f95ec27a6e0e1a87682fbb817b25f2f9d80531f.prepare/node_modules/detox/scripts
+ detoxRootPath=/Users/djhr/Library/Caches/Yarn/v6/.tmp/08757a422460db4f0967139a62ebf40c.2f95ec27a6e0e1a87682fbb817b25f2f9d80531f.prepare/node_modules/detox
++ node -p 'require('\''/Users/djhr/Library/Caches/Yarn/v6/.tmp/08757a422460db4f0967139a62ebf40c.2f95ec27a6e0e1a87682fbb817b25f2f9d80531f.prepare/node_modules/detox/package.json'\'').version'
+ detoxVersion=12.6.1
++ echo 12.6.1
++ xcodebuild -version
++ shasum
++ awk '{print $1}'
+ sha1=0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e
+ detoxFrameworkDirPath=/Users/djhr/Library/Detox/ios/0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e
+ detoxFrameworkPath=/Users/djhr/Library/Detox/ios/0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e/Detox.framework
+ main
+ '[' -d /Users/djhr/Library/Detox/ios/0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e ']'
+ '[' '!' -d /Users/djhr/Library/Detox/ios/0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e/Detox.framework ']'
+ echo '/Users/djhr/Library/Detox/ios/0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/djhr/Library/Detox/ios/0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e and trying to rebuild.'
+ rm -rf /Users/djhr/Library/Detox/ios/0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e
/Users/djhr/Library/Detox/ios/0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/djhr/Library/Detox/ios/0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e and trying to rebuild.
+ prepareAndBuildFramework
+ '[' -d /Users/djhr/Library/Caches/Yarn/v6/.tmp/08757a422460db4f0967139a62ebf40c.2f95ec27a6e0e1a87682fbb817b25f2f9d80531f.prepare/node_modules/detox/ios ']'
+ detoxSourcePath=/Users/djhr/Library/Caches/Yarn/v6/.tmp/08757a422460db4f0967139a62ebf40c.2f95ec27a6e0e1a87682fbb817b25f2f9d80531f.prepare/node_modules/detox/ios_src
+ extractSources /Users/djhr/Library/Caches/Yarn/v6/.tmp/08757a422460db4f0967139a62ebf40c.2f95ec27a6e0e1a87682fbb817b25f2f9d80531f.prepare/node_modules/detox/ios_src
+ detoxSourcePath=/Users/djhr/Library/Caches/Yarn/v6/.tmp/08757a422460db4f0967139a62ebf40c.2f95ec27a6e0e1a87682fbb817b25f2f9d80531f.prepare/node_modules/detox/ios_src
+ echo 'Extracting Detox sources...'
Extracting Detox sources...
+ mkdir -p /Users/djhr/Library/Caches/Yarn/v6/.tmp/08757a422460db4f0967139a62ebf40c.2f95ec27a6e0e1a87682fbb817b25f2f9d80531f.prepare/node_modules/detox/ios_src
+ tar -xjf /Users/djhr/Library/Caches/Yarn/v6/.tmp/08757a422460db4f0967139a62ebf40c.2f95ec27a6e0e1a87682fbb817b25f2f9d80531f.prepare/node_modules/detox/Detox-ios-src.tbz -C /Users/djhr/Library/Caches/Yarn/v6/.tmp/08757a422460db4f0967139a62ebf40c.2f95ec27a6e0e1a87682fbb817b25f2f9d80531f.prepare/node_modules/detox/ios_src
+ buildFramework /Users/djhr/Library/Caches/Yarn/v6/.tmp/08757a422460db4f0967139a62ebf40c.2f95ec27a6e0e1a87682fbb817b25f2f9d80531f.prepare/node_modules/detox/ios_src
+ detoxSourcePath=/Users/djhr/Library/Caches/Yarn/v6/.tmp/08757a422460db4f0967139a62ebf40c.2f95ec27a6e0e1a87682fbb817b25f2f9d80531f.prepare/node_modules/detox/ios_src
+ echo 'Building Detox.framework from /Users/djhr/Library/Caches/Yarn/v6/.tmp/08757a422460db4f0967139a62ebf40c.2f95ec27a6e0e1a87682fbb817b25f2f9d80531f.prepare/node_modules/detox/ios_src...'
Building Detox.framework from /Users/djhr/Library/Caches/Yarn/v6/.tmp/08757a422460db4f0967139a62ebf40c.2f95ec27a6e0e1a87682fbb817b25f2f9d80531f.prepare/node_modules/detox/ios_src...
+ mkdir -p /Users/djhr/Library/Detox/ios/0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e
+ /Users/djhr/Library/Caches/Yarn/v6/.tmp/08757a422460db4f0967139a62ebf40c.2f95ec27a6e0e1a87682fbb817b25f2f9d80531f.prepare/node_modules/detox/scripts/build_universal_framework.sh /Users/djhr/Library/Caches/Yarn/v6/.tmp/08757a422460db4f0967139a62ebf40c.2f95ec27a6e0e1a87682fbb817b25f2f9d80531f.prepare/node_modules/detox/ios_src/Detox.xcodeproj /Users/djhr/Library/Detox/ios/0e1b2e9d008dd5da9f0037c8747ef32bd8ed2b2e
child_process.js:651
    throw err;
    ^

Error: Command failed: /Users/djhr/Library/Caches/Yarn/v6/.tmp/08757a422460db4f0967139a62ebf40c.2f95ec27a6e0e1a87682fbb817b25f2f9d80531f.prepare/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:630:11)
    at Object.execFileSync (child_process.js:648:15)
    at Object.<anonymous> (/Users/djhr/Library/Caches/Yarn/v6/.tmp/08757a422460db4f0967139a62ebf40c.2f95ec27a6e0e1a87682fbb817b25f2f9d80531f.prepare/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  status: 65,
  signal: null,
  output: [ null, null, null ],
  pid: 14050,
```

Detox 12.6.1 is not compatible with XCode 12, upgrading detox solves the issue

## Repro steps

On mac with XCode 12, delete yarn caches and run `yarn install`

**Comment by Krizzu** [comment]
Is it related to AsyncStorage?

**Comment by LeeJunhui** [comment]
same issue with @djhr

**Comment by Krizzu** [comment]
Please let me know if it's related to AsyncStorage.

**Comment by djhr** [comment]
@Krizzu yes it's related to AsyncStorage
no one who is running macos with xcode 12 and hasn't cached a built version of detox on yarn caches is able to build their RN projects if they include async-storage, I have reports of people having this broken for 2 weeks now...

**Comment by djhr** [comment]
have a look at https://github.com/facebook/react-native/pull/30084
difference is react-native doesn't include detox on their deps or devdeps, so it doesn't break yarn install to everyone, but asyncstorage do

**Comment by tido64** [comment]
@djhr: AsyncStorage only has a devDependency on detox. It wouldn't be installed if you're only a consumer. Are you sure detox is coming from this package? Can you run `yarn why detox` to see which package(s) is pulling it in?

@Krizzu: Is there a plan to upgrade detox? When the CIs move to Xcode 12, we'll start seeing failing installs.

**Comment by Krizzu** [comment]
@tido64 Yes, there's a plan for that too, but first AsyncStorage will need move to its own organization ([this proposal explains it.](https://github.com/react-native-community/discussions-and-proposals/blob/master/partners/0001-organization-repository-policy.md))

**Comment by djhr** [comment]
At the moment I'm not being able to reproduce the error, on my side I use a fork of async-storage so when I upgraded detox there, I was immediately able to install, also if I would remove async-storage dependency yarn would install just fine, if I would put it back I would have that error.

Can't understand either why yarn would try to build detox since it's on devDeps as you mentioned, but it was...

**Comment by tido64** [comment]
> Can't understand either why yarn would try to build detox since it's on devDeps as you mentioned, but it was...

For future reference, you can try running `yarn why detox` to get a list of all packages pulling it in. If you're using npm, the equivalent is `npm ls detox`.

**Comment by compojoom** [comment]
This seems to happen when one tries to install from a branch:
```
yarn add https://github.com/react-native-async-storage/async-storage.git\#disable-ios-backup
```

I have no problems installing from an npm package, but trying to add it from the branch fails.
