### ISSUE TITLE
TypeError: Cannot read property 'AsyncSQLiteDBStorage' of undefined

### ISSUE THREAD

**Issue by gruckionvit** [react-native-async-storage/async-storage#543]
## Current behavior

When running `npm run test` in the [Ignite bowser boilerate](https://github.com/infinitered/ignite) with `expo`. I run into the following issue;

This occurs after installing `"@react-native-async-storage/async-storage": "^1.13.4",` and changing 

```ts
- import { AsyncStorage } from "react-native"
+ import AsyncStorage from "@react-native-async-storage/async-storage"
```

```
 FAIL   iOS  app/utils/storage/storage.test.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'AsyncSQLiteDBStorage' of undefined

      at Object.<anonymous> (node_modules/@react-native-async-storage/async-storage/lib/commonjs/RCTAsyncStorage.expo.js:21:35)
      at Object.<anonymous> (node_modules/@react-native-async-storage/async-storage/lib/commonjs/AsyncStorage.native.js:14:1)
```

No other changes have been made to the code base.

## Expected behavior

Expect the tests to run as before.

## Repro steps

1. Use the Ignite Bowser CLI tool to generate a new project.
2. Select `Bowser (React Navigation, MobX State Tree, & TypeScript) - RECOMMENDED`
3. Select `y` when asked `? Would you like to use Expo on this project?`
4. Install `"@react-native-async-storage/async-storage": "^1.13.4"`
5. Change the AsyncStorage import
6. 
```ts
- import { AsyncStorage } from "react-native"
+ import AsyncStorage from "@react-native-async-storage/async-storage"
```

## Environment

- **Platforms tested**:
  - [ ] Android
  - [ ] iOS
  - [x] macOS
  - [ ] Windows
- **AsyncStorage version**: `"version": "1.13.4",`
- **Expo version**: `"version": "40.0.1",`
- **Environment**: 

```
➜  Project git:(bug/fix-jest-failing-transform) npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 509.21 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.19.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 30
      Build Tools: 30.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Logs/Errors that may be relevant**: 

```
 FAIL   iOS  app/utils/storage/storage.test.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'AsyncSQLiteDBStorage' of undefined

      at Object.<anonymous> (node_modules/@react-native-async-storage/async-storage/lib/commonjs/RCTAsyncStorage.expo.js:21:35)
      at Object.<anonymous> (node_modules/@react-native-async-storage/async-storage/lib/commonjs/AsyncStorage.native.js:14:1)
```

I have created a `repro repo` [here](https://github.com/gruckion/Repro-repo-for-async-storage/commits/master)

**Comment by Krizzu** [comment]
Have you tried [our Jest integration guide?](https://react-native-async-storage.github.io/async-storage/docs/advanced/jest)

**Comment by gruckionvit** [comment]
I have not, I will take a look and close this if it resolve the issue. Thank you.

**Comment by Krizzu** [comment]
hey

Did it work for you or you need some more help?
