### ISSUE TITLE
can't import the package @react-native-community/async-storage properly 

### ISSUE THREAD

**Issue by kandabior** [react-native-async-storage/async-storage#553]
## Current behavior

After importing the @react-native-community/async-storage package the code won't compile and I'm getting an error message 

I'm using react-native for windows and installed via `npm install  @react-native-async-storage/async-storage`.

the import line is:
`
import AsyncStorage from '@react-native-async-storage/async-storage
`

What could be the problem?

## Environment

- **Platforms tested**:
  - [ ] Windows
- **AsyncStorage version**:
   ^1.14.0
- **Environment**:
```
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
    Memory: 4.26 GB / 15.81 GB
  Binaries:
    Node: 15.5.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.3.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: 16.8.30907.101 (Visual Studio Community 2019)
  Languages:
    Java: 15.0.1 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
    Python: 2.7.18 - C:\Python27\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: ^0.63.0-0 => 0.63.22
  npmGlobalPackages:
    *react-native*: Not Found
```
- **Logs/Errors that may be relevant**: 

```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:611:3)
    at tryReadSync (node:fs:385:20)
    at Object.readFileSync (node:fs:422:19)
    at UnableToResolveError.buildCodeFrameMessage (C:\Users\mjfc37\Documents\React\TrackProject\tracks\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:304:17)
    at new UnableToResolveError (C:\Users\mjfc37\Documents\React\TrackProject\tracks\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:290:35)
    at ModuleResolver.resolveDependency (C:\Users\mjfc37\Documents\React\TrackProject\tracks\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:191:15)
    at DependencyGraph.resolveDependency (C:\Users\mjfc37\Documents\React\TrackProject\tracks\node_modules\metro\src\node-haste\DependencyGraph.js:353:43)
    at C:\Users\mjfc37\Documents\React\TrackProject\tracks\node_modules\metro\src\lib\transformHelpers.js:271:42
    at C:\Users\mjfc37\Documents\React\TrackProject\tracks\node_modules\metro\src\Server.js:1097:37    at Generator.next (<anonymous>)
```

**Comment by tido64** [comment]
Did you install `@react-native-community/async-storage` or `@react-native-async-storage/async-storage`? The former won't work as we've renamed the package.

**Comment by kandabior** [comment]
> Did you install `@react-native-community/async-storage` or `@react-native-async-storage/async-storage`? The former won't work as we've renamed the package.

I installed `@react-native-async-storage/async-storage` 

I edited the question.

**Comment by tido64** [comment]
Sorry, looking at the error message, it sounds like you're having some kind of caching issue. Did you try clearing out everything (e.g. deleting `node_modules`) and running `npm install` again?

This is not an issue with AsyncStorage so I will be closing this issue.
