### ISSUE TITLE
JEST - [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null 

### ISSUE THREAD

**Issue by TommyLeong** [react-native-async-storage/async-storage#574]
## You want to:  
While running `npm jest`, I was thrown by this error here.
```
 FAIL  __tests__/App-test.js
  ● Test suite failed to run

    [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

    To fix this issue try these steps:

      • Run `react-native link @react-native-community/async-storage` in the project root.

      • Rebuild and restart the app.

      • Run the packager with `--reset-cache` flag.

      • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app.

      • If this happens while testing with Jest, check out docs how to integrate AsyncStorage with it: https://react-native-community.github.io/async-storage/docs/advanced/jest

    If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-async-storage/issues

      at Object.<anonymous> (node_modules/@react-native-community/async-storage/lib/commonjs/AsyncStorage.native.js:17:9)
      at Object.<anonymous> (node_modules/@react-native-community/async-storage/lib/commonjs/index.js:5:1)
```

## Details:
As of current, I'm not doing any unit test that has anything to do with AsyncStorage. Was simply running the default test given while project creation
```
/**
 * @format
 */

import 'react-native';
import React from 'react';
import App from '../App';

// Note: test renderer must be required after react-native.
import renderer from 'react-test-renderer';

it('renders correctly', () => {
  renderer.create(<App />);
});

```

However I've also tired setting up the mock directory according to the [steps given from AsyncStorage lib](https://react-native-async-storage.github.io/async-storage/docs/advanced/jest/).  Which end up with another error as following: 

**New Error**
```
 FAIL  __tests__/App-test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'default' of undefined

      1 | import mockAsyncStorage from './__mocks__/@react-native-async-storage/async-storage';
    > 2 | 
        | ^
      3 | jest.mock('@react-native-async-storage/async-storage', () => mockAsyncStorage);

      at jest.setup.js:2:24
      at Object.<anonymous> (jest.setup.js:7:44)
```

**Files**
`/__mocks__/@react-native-async-storage/async-storage.js`
```
export default from '@react-native-async-storage/async-storage/jest/async-storage-mock'
```

`package.json` (only the Jest part is showing)
```
"jest": {
    "preset": "react-native",
    "setupFiles": [
      "./jest.setup.js"
    ]
  }
```

`jest.setup.js`
```
import mockAsyncStorage from './__mocks__/@react-native-async-storage/async-storage';

jest.mock('@react-native-async-storage/async-storage', () => mockAsyncStorage);
```

**Comment by radko93** [comment]
I'm also having this issue.

**Comment by Krizzu** [comment]
Hey @TommyLeong 

From the documentation, you can see you have two options to apply mock: either `__mocks__` directory or jest setup file.

If you want to use `setup` file, you have to create a new file and point `jest` to use it:

```
"jest": {
  "setupFiles": ["./path/to/jestSetupFile.js"]
}
```

Then, inside the file, you have import and use the `mock` from Async Storage module, instead of your `__mock__` directory

```
import mockAsyncStorage from '@react-native-async-storage/async-storage/jest/async-storage-mock';

jest.mock('@react-native-async-storage/async-storage', () => mockAsyncStorage);
```


@radko93  👋 

Please provide bit more details to the problem you see

**Comment by radko93** [comment]
1. Using async storage directly in the project codebase works.
2. Importing a node module that uses async storage under the hood does not work.

Seems like it might be a jest issue.

Our current setup:
 "@react-native-async-storage/async-storage": "^1.15.2",
"jest": "^26.6.3"

```
import { jest } from '@jest/globals';
import mockAsyncStorage from '@react-native-async-storage/async-storage/jest/async-storage-mock';

jest.mock('@react-native-async-storage/async-storage', () => mockAsyncStorage);

jest.mock('react-native-agora', () => ({
  VideoStreamType: {
    High: 0,
    Low: 1,
  },
}));
```

```
"jest": {
    "setupFiles": [
      "./jestSetupFile.js"
    ],
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "globals": {
      "window": {}
    }
  }
  ```

**Comment by BenjaminSAILcloud** [comment]
Hi everyone,

I have the same issue where even if I follow the [doc](https://react-native-async-storage.github.io/async-storage/docs/advanced/jest/), I still get errors for the two ways.

I am only trying to run the default RN test:
```tsx
/**
 * @format
 */

import 'react-native';

import App from '../src/index';
import React from 'react';
// Note: test renderer must be required after react-native.
import renderer from 'react-test-renderer';

it('renders correctly', () => {
  renderer.create(<App />);
});
```

<details>
<summary>Details for Jest setup file</summary>
<h2>Error:</h2>

```js
 FAIL  __tests__/App.test.tsx
  ● Test suite failed to run

    [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

    To fix this issue try these steps:

      • Run `react-native link @react-native-async-storage/async-storage` in the project root.

      • Rebuild and restart the app.

      • Run the packager with `--reset-cache` flag.

      • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app.

      • If this happens while testing with Jest, check out docs how to integrate AsyncStorage with it: https://react-native-async-storage.github.io/async-storage/docs/advanced/jest

    If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-async-storage/react-native-async-storage/issues

      at Object.<anonymous> (node_modules/@react-native-async-storage/async-storage/lib/commonjs/AsyncStorage.native.js:17:9)
      at Object.<anonymous> (node_modules/@react-native-async-storage/async-storage/lib/commonjs/index.js:6:1)
```

<h2>package.json</h2>

```json
"jest": {
    "setupFiles": [
      "./tests/jest.setup.js"
    ]
  }
```

<h2>tests/jest.setup.js</h2>

```js
import {jest} from '@jest/globals'; // tried with and without this line
import mockAsyncStorage from '@react-native-async-storage/async-storage/jest/async-storage-mock';

jest.mock('@react-native-async-storage/async-storage', () => mockAsyncStorage);

```
</details>
<details>
<summary>Details for direct mock</summary>
<h2>Error:</h2>

```js
 FAIL  __tests__/App.test.tsx
  ● Test suite failed to run

    TypeError: Cannot read property 'default' of undefined

      11 | import renderer from 'react-test-renderer';
      12 |
    > 13 | jest.mock('@react-native-async-storage/async-storage', () => mockAsyncStorage);
         |                                                              ^
      14 |
      15 | it('renders correctly', () => {
      16 |   renderer.create(<App />);

      at __tests__/App.test.tsx:13:62
      at Object.<anonymous> (src/providers/global_provider.js:3:1)
      at Object.<anonymous> (src/index.js:3:1)
```

<h2>__mocks__/@react-native-async-storage/async-storage.js</h2>

```js
export default from '@react-native-async-storage/async-storage/jest/async-storage-mock';

```

<h2>App.test.tsx</h2>

```tsx
/**
 * @format
 */

import 'react-native';

import App from '../src/index';
import React from 'react';
import mockAsyncStorage from '@react-native-async-storage/async-storage/jest/async-storage-mock';
// Note: test renderer must be required after react-native.
import renderer from 'react-test-renderer';

jest.mock('@react-native-async-storage/async-storage', () => mockAsyncStorage);

it('renders correctly', () => {
  renderer.create(<App />);
});

```
</details>
