### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by kailashchand-arcgate** [react-native-async-storage/async-storage#585]
## Description
My APP is based on react native. For Tracking purpose I have implemented Firebase Crashlytics, It seems to me that this issue is a collection of different edge case issues, a few related to libraries "react-native": "0.63.4" and some related to "@react-native-async-storage/async-storage": "^1.13.2". 

## Device Info:
Brand:samsung
Model:Galaxy S10+
Orientation: Portrait
RAM free: 2.65 GB
Disk free: 45.78 GB
Version:9
Orientation: Portrait
Rooted:No

## React Native version:
react: "16.13.1",
react-native: "0.63.4",
clevertap-react-native: "^0.5.0",
smartlook-react-native-wrapper: "^0.39.0"
@react-native-firebase/analytics: "^10.1.0",
"@react-native-async-storage/async-storage": "^1.13.2",

## Steps To Reproduce
Tried to reproduce this issue in Android emulator 9 but didn't get any crash at my end. This crash is happened with my clients build. I have came to know about this crash from my Firebase Crashlytics. 

## Expected Results
Crash shouldn’t happen. Crash logs should be more descriptive and understandable for React-Native developer. Specially for JavaScript development. Because I am not much aware about core java related programming.

## Snack, code example, screenshot, or link to a repository:
Sorry, due to company IT policy I am unable to share code. Screenshot attached at very bottom of the thread of Firebase Crashlytics.

## My Investigation
 React-Native 0.63 have some major issues, so after release of 0.64, React-Native stop support for older device below then Android 5.0 and iOS 11. **So might be react native 0.63 will be culprit for this crash**. https://github.com/facebook/react-native#-requirements

## Firebase Crashlytics Information
`Fatal Exception: java.lang.RuntimeException`
`An error occurred while executing doInBackground()`
```sh
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:354)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at com.reactnativecommunity.asyncstorage.AsyncStorageModule$SerialExecutor$1.run(AsyncStorageModule.java:63)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```
```sh
Caused by java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.rdiscovery/databases/RKStorage
       at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
       at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1707)
       at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1583)
       at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1751)
       at com.reactnativecommunity.asyncstorage.AsyncStorageModule$1.doInBackgroundGuarded(AsyncStorageModule.java:159)
       at com.reactnativecommunity.asyncstorage.AsyncStorageModule$1.doInBackgroundGuarded(AsyncStorageModule.java:146)
       at com.facebook.react.bridge.GuardedAsyncTask.doInBackground(GuardedAsyncTask.java:36)
       at com.facebook.react.bridge.GuardedAsyncTask.doInBackground(GuardedAsyncTask.java:20)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at com.reactnativecommunity.asyncstorage.AsyncStorageModule$SerialExecutor$1.run(AsyncStorageModule.java:63)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

![Screenshot_6](https://user-images.githubusercontent.com/69476046/114408011-a0e31a80-9bc6-11eb-918a-a579ce249ed5.png)

**Comment by Krizzu** [comment]
Hey,

Do you have any work in a timeout scheduled to do after app goes to the background? To me it looks like the app tries to save/read from AsyncStorage when the db connection is already closed ([when the RN Host is killed](https://github.com/react-native-async-storage/async-storage/blob/master/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java#L102-L106))

**Comment by MajkellVZ** [comment]
Had the same issue on `react-native: 0.66.4 async-storage: 1.16.1`. The crash happened in production and wasn't able to reproduce it. The phone it crashed on was Google Pixel 6, Android 12L (SDK 32).

```
java.lang.RuntimeException: 
  at android.os.AsyncTask$4.done (AsyncTask.java:415)
  at java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:383)
  at java.util.concurrent.FutureTask.setException (FutureTask.java:252)
  at java.util.concurrent.FutureTask.run (FutureTask.java:271)
  at com.reactnativecommunity.asyncstorage.SerialExecutor$1.run (SerialExecutor.java:25)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:920)
Caused by: java.lang.IllegalStateException: 
  at android.database.sqlite.SQLiteClosable.acquireReference (SQLiteClosable.java:58)
  at android.database.sqlite.SQLiteDatabase.queryWithFactory (SQLiteDatabase.java:1388)
  at android.database.sqlite.SQLiteDatabase.query (SQLiteDatabase.java:1264)
  at android.database.sqlite.SQLiteDatabase.query (SQLiteDatabase.java:1432)
  at com.reactnativecommunity.asyncstorage.AsyncStorageModule$1.doInBackgroundGuarded (AsyncStorageModule.java:132)
  at com.reactnativecommunity.asyncstorage.AsyncStorageModule$1.doInBackgroundGuarded (AsyncStorageModule.java:119)
  at com.facebook.react.bridge.GuardedAsyncTask.doInBackground (GuardedAsyncTask.java:36)
  at com.facebook.react.bridge.GuardedAsyncTask.doInBackground (GuardedAsyncTask.java:20)
  at android.os.AsyncTask$3.call (AsyncTask.java:394)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
```
