### ISSUE TITLE
AsyncStorageModule.java uses or overrides a deprecated API. Note: Recompile with -Xlint:deprecation for details.

### ISSUE THREAD

**Issue by Luckygirlllll** [react-native-async-storage/async-storage#609]
## Current behavior

got this error, when run Android today.

## Expected behavior

don't see an error.

## Repro steps

add library 
run android

## Environment

- **Platforms tested**:
  - [x ] Android
  - [ ] iOS
  - [ ] macOS
  - [ ] Windows
- **AsyncStorage version**:   1.15.4
- **Expo version**: 
- **Environment**:
  

System:
    OS: macOS 11.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 111.94 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/iryna/.rvm/gems/ruby-2.6.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_161 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1
    react-native: 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

- **Logs/Errors that may be relevant**: 

@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by hayyaun** [comment]
+1

My app was working fine and still build-able but I haven't touched the code for weeks. Yesterday I got this error and today I updated from @react-native-community/async-storage to @react-native-async-storage/async-storage but still getting errors below:

```
Note: D:\..\node_modules\@react-native-async-storage\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStorageModule.java uses or overrides a deprecated API.
```

```
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find sqlite-framework-2.1.0.aar (androidx.sqlite:sqlite-framework:2.1.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/sqlite/sqlite-framework/2.1.0/sqlite-framework-2.1.0.aar
   > Could not find sqlite-2.1.0.aar (androidx.sqlite:sqlite:2.1.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/sqlite/sqlite/2.1.0/sqlite-2.1.0.aar
```

The mentioned files were unreachable from Google on 20 May, and today they are accessible but I'm stilling facing the same error.

**Comment by Krizzu** [comment]
@Luckygirlllll  hey,

It seems like it's not the main error, rather more like a warning. Can you double check that? Or maybe include whole console output you get.


@hayyaun 
`Could not find sqlite-framework-2.1.0.aar (androidx.sqlite:sqlite-framework:2.1.0).`
That's not related to AsyncStorage and `uses or overrides a deprecated API.` is just a note/warning. Can you provide whole gradle error message to help out investigating it?

**Comment by hayyaun** [comment]
> @Luckygirlllll hey,
> 
> It seems like it's not the main error, rather more like a warning. Can you double check that? Or maybe include whole console output you get.
> 
> @hayyaun
> `Could not find sqlite-framework-2.1.0.aar (androidx.sqlite:sqlite-framework:2.1.0).`
> That's not related to AsyncStorage and `uses or overrides a deprecated API.` is just a note/warning. Can you provide whole gradle error message to help out investigating it?

I think gradle is taking it as main error.
here is the complete log

```
[1] > react-native run-android
[1]
[1] info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
[1] Jetifier found 1153 file(s) to forward-jetify. Using 8 workers...
[1] info JS server already running.
[1] info Installing the app...
[1] > Task :app:generatePackageList
[1] > Task :app:preBuild
[1] > Task :app:preDebugBuild
[1] > Task :react-native-async-storage_async-storage:preBuild UP-TO-DATE
[1] > Task :react-native-async-storage_async-storage:preDebugBuild UP-TO-DATE
[1] > Task :react-native-community_masked-view:preBuild UP-TO-DATE
> Task :react-native-community_masked-view:preDebugBuild UP-TO-DATE
[1] > Task :react-native-community_netinfo:preBuild UP-TO-DATE
> Task :react-native-community_netinfo:preDebugBuild UP-TO-DATE
[1] > Task :react-native-gesture-handler:preBuild UP-TO-DATE
[1] > Task :react-native-community_netinfo:compileDebugAidl NO-SOURCE
[1] > Task :react-native-gesture-handler:preDebugBuild UP-TO-DATE
[1] > Task :react-native-reanimated:preBuild UP-TO-DATE
[1] > Task :react-native-reanimated:preDebugBuild UP-TO-DATE
[1] > Task :react-native-safe-area-context:preBuild UP-TO-DATE
[1] > Task :react-native-safe-area-context:preDebugBuild UP-TO-DATE
[1] > Task :react-native-async-storage_async-storage:compileDebugAidl NO-SOURCE
[1] > Task :react-native-community_masked-view:compileDebugAidl NO-SOURCE
[1] > Task :react-native-gesture-handler:compileDebugAidl NO-SOURCE
[1] > Task :react-native-reanimated:compileDebugAidl NO-SOURCE
> Task :react-native-safe-area-context:compileDebugAidl NO-SOURCE
[1] > Task :react-native-screens:preBuild UP-TO-DATE
[1] > Task :react-native-screens:preDebugBuild UP-TO-DATE
[1] > Task :react-native-splash-screen:preBuild UP-TO-DATE
[1] > Task :react-native-splash-screen:preDebugBuild UP-TO-DATE
[1] > Task :react-native-splash-screen:compileDebugAidl NO-SOURCE
[1] > Task :react-native-svg:preBuild UP-TO-DATE
[1] > Task :react-native-svg:preDebugBuild UP-TO-DATE
[1] > Task :react-native-svg:compileDebugAidl NO-SOURCE
[1] > Task :react-native-vector-icons:preBuild UP-TO-DATE
[1] > Task :react-native-vector-icons:preDebugBuild UP-TO-DATE
[1] > Task :react-native-vector-icons:compileDebugAidl NO-SOURCE
[1] > Task :react-native-async-storage_async-storage:packageDebugRenderscript NO-SOURCE
[1] > Task :react-native-community_masked-view:packageDebugRenderscript NO-SOURCE
[1] > Task :react-native-community_netinfo:packageDebugRenderscript NO-SOURCE
[1] > Task :react-native-gesture-handler:packageDebugRenderscript NO-SOURCE
[1] > Task :react-native-reanimated:packageDebugRenderscript NO-SOURCE
[1] > Task :react-native-safe-area-context:packageDebugRenderscript NO-SOURCE
[1] > Task :react-native-screens:packageDebugRenderscript NO-SOURCE
[1] > Task :react-native-splash-screen:packageDebugRenderscript NO-SOURCE
[1] > Task :react-native-svg:packageDebugRenderscript NO-SOURCE
[1] > Task :react-native-screens:compileDebugAidl NO-SOURCE
[1] > Task :app:compileDebugAidl NO-SOURCE
[1] > Task :react-native-vector-icons:packageDebugRenderscript NO-SOURCE
[1] > Task :app:compileDebugRenderscript NO-SOURCE
[1] > Task :app:checkDebugManifest UP-TO-DATE
[1] > Task :app:generateDebugBuildConfig UP-TO-DATE
[1] > Task :react-native-async-storage_async-storage:checkDebugManifest
[1] > Task :react-native-async-storage_async-storage:compileDebugRenderscript NO-SOURCE
[1] > Task :react-native-async-storage_async-storage:generateDebugBuildConfig
[1] > Task :react-native-async-storage_async-storage:generateDebugResValues
[1] > Task :react-native-async-storage_async-storage:generateDebugResources
[1] > Task :react-native-async-storage_async-storage:packageDebugResources
[1] > Task :react-native-community_masked-view:compileDebugRenderscript NO-SOURCE
[1] > Task :react-native-community_masked-view:checkDebugManifest UP-TO-DATE
[1] > Task :react-native-community_masked-view:generateDebugBuildConfig UP-TO-DATE
[1] > Task :react-native-async-storage_async-storage:parseDebugLibraryResources
[1] > Task :react-native-async-storage_async-storage:processDebugManifest
[1] > Task :react-native-community_masked-view:generateDebugResValues UP-TO-DATE
[1] > Task :react-native-community_masked-view:generateDebugResources UP-TO-DATE
[1] > Task :react-native-community_masked-view:packageDebugResources UP-TO-DATE
[1] > Task :react-native-community_masked-view:parseDebugLibraryResources UP-TO-DATE
[1] > Task :react-native-community_masked-view:processDebugManifest UP-TO-DATE
[1] > Task :react-native-community_masked-view:generateDebugRFile UP-TO-DATE
[1] > Task :react-native-community_masked-view:javaPreCompileDebug UP-TO-DATE
[1] > Task :react-native-community_masked-view:compileDebugJavaWithJavac UP-TO-DATE
[1] > Task :react-native-community_masked-view:bundleLibCompileDebug UP-TO-DATE
> Task :react-native-async-storage_async-storage:javaPreCompileDebug
[1] > Task :react-native-community_netinfo:compileDebugRenderscript NO-SOURCE
[1] > Task :react-native-community_netinfo:checkDebugManifest UP-TO-DATE
[1] > Task :react-native-community_netinfo:generateDebugBuildConfig UP-TO-DATE
[1] > Task :react-native-community_netinfo:generateDebugResValues UP-TO-DATE
[1] > Task :react-native-community_netinfo:generateDebugResources UP-TO-DATE
[1] > Task :react-native-community_netinfo:packageDebugResources UP-TO-DATE
[1] > Task :react-native-community_netinfo:parseDebugLibraryResources UP-TO-DATE
[1] > Task :react-native-community_netinfo:processDebugManifest UP-TO-DATE
[1] > Task :react-native-community_netinfo:generateDebugRFile UP-TO-DATE
[1] > Task :react-native-community_netinfo:javaPreCompileDebug UP-TO-DATE
[1] > Task :react-native-community_netinfo:compileDebugJavaWithJavac UP-TO-DATE
[1] > Task :react-native-community_netinfo:bundleLibCompileDebug UP-TO-DATE
[1] > Task :react-native-gesture-handler:checkDebugManifest UP-TO-DATE
[1] > Task :react-native-gesture-handler:compileDebugRenderscript NO-SOURCE
[1] > Task :react-native-gesture-handler:generateDebugBuildConfig UP-TO-DATE
[1] > Task :react-native-gesture-handler:generateDebugResValues UP-TO-DATE
[1] > Task :react-native-gesture-handler:generateDebugResources UP-TO-DATE
[1] > Task :react-native-gesture-handler:packageDebugResources UP-TO-DATE
[1] > Task :react-native-gesture-handler:parseDebugLibraryResources UP-TO-DATE
[1] > Task :react-native-gesture-handler:processDebugManifest UP-TO-DATE
[1] > Task :react-native-gesture-handler:generateDebugRFile UP-TO-DATE
[1] > Task :react-native-gesture-handler:javaPreCompileDebug UP-TO-DATE
[1] > Task :react-native-gesture-handler:compileDebugJavaWithJavac UP-TO-DATE
[1] > Task :react-native-gesture-handler:bundleLibCompileDebug UP-TO-DATE
[1] > Task :react-native-async-storage_async-storage:generateDebugRFile
[1] 
[1] > Task :react-native-async-storage_async-storage:compileDebugJavaWithJavac
[1] 
> Task :react-native-reanimated:checkDebugManifest UP-TO-DATE
[1] > Task :react-native-reanimated:generateDebugBuildConfig UP-TO-DATE
[1] > Task :react-native-reanimated:compileDebugRenderscript NO-SOURCE
[1] > Task :react-native-reanimated:generateDebugResValues UP-TO-DATE
[1] > Task :react-native-reanimated:generateDebugResources UP-TO-DATE
[1] > Task :react-native-reanimated:packageDebugResources UP-TO-DATE
[1] > Task :react-native-reanimated:parseDebugLibraryResources UP-TO-DATE
[1] > Task :react-native-reanimated:processDebugManifest UP-TO-DATE
[1] > Task :react-native-reanimated:generateDebugRFile UP-TO-DATE
[1] > Task :react-native-reanimated:javaPreCompileDebug UP-TO-DATE
[1] > Task :react-native-reanimated:compileDebugJavaWithJavac UP-TO-DATE
[1] > Task :react-native-reanimated:bundleLibCompileDebug UP-TO-DATE
[1] > Task :react-native-async-storage_async-storage:bundleLibCompileDebug
[1] > Task :react-native-safe-area-context:checkDebugManifest UP-TO-DATE
[1] > Task :react-native-safe-area-context:compileDebugRenderscript NO-SOURCE
[1] > Task :react-native-safe-area-context:generateDebugBuildConfig UP-TO-DATE
[1] > Task :react-native-safe-area-context:generateDebugResValues UP-TO-DATE
[1] > Task :react-native-safe-area-context:generateDebugResources UP-TO-DATE
[1] > Task :react-native-safe-area-context:packageDebugResources UP-TO-DATE
[1] > Task :react-native-safe-area-context:parseDebugLibraryResources UP-TO-DATE
[1] > Task :react-native-safe-area-context:processDebugManifest UP-TO-DATE
[1] > Task :react-native-safe-area-context:generateDebugRFile UP-TO-DATE
> Task :react-native-safe-area-context:javaPreCompileDebug UP-TO-DATE
[1] > Task :react-native-safe-area-context:compileDebugJavaWithJavac UP-TO-DATE
[1] > Task :react-native-safe-area-context:bundleLibCompileDebug UP-TO-DATE
[1] > Task :react-native-screens:checkDebugManifest UP-TO-DATE
[1] > Task :react-native-screens:generateDebugBuildConfig UP-TO-DATE
[1] > Task :react-native-screens:compileDebugRenderscript NO-SOURCE
[1] > Task :react-native-screens:generateDebugResValues UP-TO-DATE
[1] > Task :react-native-screens:generateDebugResources UP-TO-DATE
[1] > Task :react-native-screens:packageDebugResources UP-TO-DATE
[1] > Task :react-native-screens:parseDebugLibraryResources UP-TO-DATE
> Task :react-native-screens:processDebugManifest UP-TO-DATE
[1] > Task :react-native-screens:generateDebugRFile UP-TO-DATE
[1] > Task :react-native-screens:javaPreCompileDebug UP-TO-DATE
[1] > Task :react-native-screens:compileDebugJavaWithJavac UP-TO-DATE
> Task :react-native-screens:bundleLibCompileDebug UP-TO-DATE
[1] > Task :react-native-splash-screen:checkDebugManifest UP-TO-DATE
[1] > Task :react-native-splash-screen:compileDebugRenderscript NO-SOURCE
[1] > Task :react-native-splash-screen:generateDebugBuildConfig UP-TO-DATE
[1] > Task :react-native-splash-screen:generateDebugResValues UP-TO-DATE
[1] > Task :react-native-splash-screen:generateDebugResources UP-TO-DATE
[1] > Task :react-native-splash-screen:packageDebugResources UP-TO-DATE
[1] > Task :react-native-splash-screen:parseDebugLibraryResources UP-TO-DATE
[1] > Task :react-native-splash-screen:processDebugManifest UP-TO-DATE
[1] > Task :react-native-splash-screen:generateDebugRFile UP-TO-DATE
[1] > Task :react-native-splash-screen:javaPreCompileDebug UP-TO-DATE
[1] > Task :react-native-splash-screen:compileDebugJavaWithJavac UP-TO-DATE
[1] > Task :react-native-splash-screen:bundleLibCompileDebug UP-TO-DATE
[1] > Task :react-native-svg:compileDebugRenderscript NO-SOURCE
[1] > Task :react-native-svg:checkDebugManifest UP-TO-DATE
[1] > Task :react-native-svg:generateDebugBuildConfig UP-TO-DATE
[1] > Task :react-native-svg:generateDebugResValues UP-TO-DATE
[1] > Task :react-native-svg:generateDebugResources UP-TO-DATE
[1] > Task :react-native-svg:packageDebugResources UP-TO-DATE
[1] > Task :react-native-svg:parseDebugLibraryResources UP-TO-DATE
[1] > Task :react-native-svg:processDebugManifest UP-TO-DATE
[1] > Task :react-native-svg:generateDebugRFile UP-TO-DATE
[1] > Task :react-native-svg:javaPreCompileDebug UP-TO-DATE
[1] > Task :react-native-svg:compileDebugJavaWithJavac UP-TO-DATE
[1] > Task :react-native-svg:bundleLibCompileDebug UP-TO-DATE
> Task :react-native-vector-icons:checkDebugManifest UP-TO-DATE
[1] > Task :react-native-vector-icons:generateDebugBuildConfig UP-TO-DATE
[1] > Task :react-native-vector-icons:compileDebugRenderscript NO-SOURCE
[1] > Task :react-native-vector-icons:generateDebugResValues UP-TO-DATE
[1] > Task :react-native-vector-icons:generateDebugResources UP-TO-DATE
[1] > Task :react-native-vector-icons:packageDebugResources UP-TO-DATE
[1] > Task :react-native-vector-icons:parseDebugLibraryResources UP-TO-DATE
[1] > Task :react-native-vector-icons:processDebugManifest UP-TO-DATE
[1] > Task :react-native-vector-icons:generateDebugRFile UP-TO-DATE
[1] > Task :react-native-vector-icons:javaPreCompileDebug UP-TO-DATE
[1] > Task :react-native-vector-icons:compileDebugJavaWithJavac UP-TO-DATE
[1] > Task :react-native-vector-icons:bundleLibCompileDebug UP-TO-DATE
[1] > Task :app:mergeDebugShaders UP-TO-DATE
[1] > Task :app:compileDebugShaders UP-TO-DATE
[1] > Task :app:generateDebugAssets UP-TO-DATE
[1] > Task :react-native-async-storage_async-storage:mergeDebugShaders
[1] > Task :react-native-async-storage_async-storage:compileDebugShaders
[1] > Task :react-native-async-storage_async-storage:generateDebugAssets
[1] > Task :react-native-async-storage_async-storage:packageDebugAssets
[1] > Task :react-native-community_masked-view:mergeDebugShaders UP-TO-DATE
[1] > Task :react-native-community_masked-view:compileDebugShaders UP-TO-DATE
[1] > Task :react-native-community_masked-view:generateDebugAssets UP-TO-DATE
[1] > Task :react-native-community_masked-view:packageDebugAssets UP-TO-DATE
[1] > Task :react-native-community_netinfo:mergeDebugShaders UP-TO-DATE
[1] > Task :react-native-community_netinfo:compileDebugShaders UP-TO-DATE
[1] > Task :react-native-community_netinfo:generateDebugAssets UP-TO-DATE
[1] > Task :react-native-community_netinfo:packageDebugAssets UP-TO-DATE
[1] > Task :react-native-gesture-handler:mergeDebugShaders UP-TO-DATE
[1] > Task :react-native-gesture-handler:compileDebugShaders UP-TO-DATE
[1] > Task :react-native-gesture-handler:generateDebugAssets UP-TO-DATE
[1] > Task :react-native-gesture-handler:packageDebugAssets UP-TO-DATE
[1] > Task :react-native-reanimated:mergeDebugShaders UP-TO-DATE
[1] > Task :react-native-reanimated:compileDebugShaders UP-TO-DATE
[1] > Task :react-native-reanimated:generateDebugAssets UP-TO-DATE
[1] > Task :react-native-reanimated:packageDebugAssets UP-TO-DATE
[1] > Task :react-native-safe-area-context:mergeDebugShaders UP-TO-DATE
[1] > Task :react-native-safe-area-context:compileDebugShaders UP-TO-DATE
[1] > Task :react-native-safe-area-context:generateDebugAssets UP-TO-DATE
[1] > Task :react-native-safe-area-context:packageDebugAssets UP-TO-DATE
[1] > Task :react-native-screens:mergeDebugShaders UP-TO-DATE
[1] > Task :react-native-screens:compileDebugShaders UP-TO-DATE
[1] > Task :react-native-screens:generateDebugAssets UP-TO-DATE
[1] > Task :react-native-screens:packageDebugAssets UP-TO-DATE
[1] > Task :react-native-splash-screen:mergeDebugShaders UP-TO-DATE
[1] > Task :react-native-splash-screen:compileDebugShaders UP-TO-DATE
[1] > Task :react-native-splash-screen:generateDebugAssets UP-TO-DATE
[1] > Task :react-native-splash-screen:packageDebugAssets UP-TO-DATE
[1] > Task :react-native-svg:mergeDebugShaders UP-TO-DATE
[1] > Task :react-native-svg:compileDebugShaders UP-TO-DATE
[1] > Task :react-native-svg:generateDebugAssets UP-TO-DATE
[1] > Task :react-native-svg:packageDebugAssets UP-TO-DATE
[1] > Task :react-native-vector-icons:mergeDebugShaders UP-TO-DATE
[1] > Task :react-native-vector-icons:compileDebugShaders UP-TO-DATE
[1] > Task :react-native-vector-icons:generateDebugAssets UP-TO-DATE
[1] > Task :react-native-vector-icons:packageDebugAssets UP-TO-DATE
[1] > Task :app:mergeDebugAssets FAILED
[1] > Task :app:javaPreCompileDebug
[1]
[1] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[1] Use '--warning-mode all' to show the individual deprecation warnings.
[1] See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
[1] 137 actionable tasks: 16 executed, 121 up-to-date
[1] Note: D:\..\node_modules\@react-native-async-storage\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStorageModule.java uses or overrides a deprecated API.
[1] Note: Recompile with -Xlint:deprecation for details.
[1] Note: D:\..\node_modules\@react-native-async-storage\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStoragePackage.java uses unchecked 
or unsafe operations.
[1] Note: Recompile with -Xlint:unchecked for details.
[1]
[1] FAILURE: Build failed with an exception.
[1]
[1] * What went wrong:
[1] Execution failed for task ':app:mergeDebugAssets'.
[1] > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
[1]    > Could not find sqlite-framework-2.1.0.aar (androidx.sqlite:sqlite-framework:2.1.0).
[1]      Searched in the following locations:
[1]          https://dl.google.com/dl/android/maven2/androidx/sqlite/sqlite-framework/2.1.0/sqlite-framework-2.1.0.aar
[1]    > Could not find sqlite-2.1.0.aar (androidx.sqlite:sqlite:2.1.0).
[1]      Searched in the following locations:
[1]          https://dl.google.com/dl/android/maven2/androidx/sqlite/sqlite/2.1.0/sqlite-2.1.0.aar
[1]
[1] * Try:
[1] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[1]
[1] * Get more help at https://help.gradle.org
[1]
[1] BUILD FAILED in 9s
[1]
[1] error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
[1] Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
[1] Note: D:\..\node_modules\@react-native-async-storage\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStorageModule.java uses or overrides a deprecated API.
[1] Note: Recompile with -Xlint:deprecation for details.
[1] Note: D:\..\node_modules\@react-native-async-storage\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStoragePackage.java uses unchecked 
or unsafe operations.
[1] Note: Recompile with -Xlint:unchecked for details.
[1]
[1] FAILURE: Build failed with an exception.
[1]
[1] * What went wrong:
[1] Execution failed for task ':app:mergeDebugAssets'.
[1] > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
[1]    > Could not find sqlite-framework-2.1.0.aar (androidx.sqlite:sqlite-framework:2.1.0).
[1]      Searched in the following locations:
[1]          https://dl.google.com/dl/android/maven2/androidx/sqlite/sqlite-framework/2.1.0/sqlite-framework-2.1.0.aar
[1]    > Could not find sqlite-2.1.0.aar (androidx.sqlite:sqlite:2.1.0).
[1]      Searched in the following locations:
[1]          https://dl.google.com/dl/android/maven2/androidx/sqlite/sqlite/2.1.0/sqlite-2.1.0.aar
[1]
[1] * Try:
[1] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[1]
[1] * Get more help at https://help.gradle.org
[1]
[1] BUILD FAILED in 9s
[1]
[1]     at makeError (D:\..\node_modules\execa\index.js:174:9)
[1]     at D:\..\node_modules\execa\index.js:278:16
[1]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[1]     at async runOnAllDevices (D:\..\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
[1]     at async Command.handleAction (D:\..\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:186:9)
[1] info Run CLI with --verbose flag for more details.
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! bamachoub-mobile@1.1.0 android: `react-native run-android`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the bamachoub-mobile@1.1.0 android script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     C:\Users\Hayyaun\AppData\Roaming\npm-cache\_logs\2021-05-21T16_04_11_528Z-debug.log
```

Thank you

**Comment by tido64** [comment]
@hayyaun AsyncStorage does not use `sqlite-framework`. Something else has a dependency on it.

**Comment by hayyaun** [comment]
> @hayyaun AsyncStorage does not use `sqlite-framework`. Something else has a dependency on it.

The error says, there is something wrong in ```AsyncStorageModule.java``` file.
Probably relate to line 11

https://github.com/react-native-async-storage/async-storage/blob/864c64bd0f6414c8959548ec237637a82b7faec3/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java#L11

**Comment by tido64** [comment]
My bad, I was on an older branch and couldn't find any references to `androidx.sqlite`. I do see it on latest because we've added support for Room. Still, `android.database.sqlite` is the "older" implementation of SQLite and is not related to `sqlite-framework` at all. It can therefore not cause the issue you're seeing. I tried manually downloading both of the URLs that are failing on your machine and it works fine to me, so it must be a network issue on your side.

**Comment by hayyaun** [comment]
> My bad, I was on an older branch and couldn't find any references to `androidx.sqlite`. I do see it on latest because we've added support for Room. Still, `android.database.sqlite` is the "older" implementation of SQLite and is not related to `sqlite-framework` at all. It can therefore not cause the issue you're seeing. I tried manually downloading both of the URLs that are failing on your machine and it works fine to me, so it must be a network issue on your side.

I see, thanks, I can download files either. But still getting same error on ```react-native run-android```.

**Comment by Krizzu** [comment]
@hayyaun 
Can you try to list a dependency graph by using gradle's `dependencies` task? With **standard** RN app, inside `android` directory, call `./gradlew app:dependencies`, it would list dependencies used by a project. Look for `sqlite-framework`, see which package requires it.

**Comment by tido64** [comment]
@hayyaun: As a workaround for your network issue, you can also try downgrading AsyncStorage to v1.14.1. That version does not have Room and will not pull in `sqlite-framework`. If you're still seeing it's definitely not AsyncStorage.

**Comment by hayyaun** [comment]
Here are the deps installed.

[deps.log](https://github.com/react-native-async-storage/async-storage/files/6526134/deps.log)

**Comment by hayyaun** [comment]
> @hayyaun: As a workaround for your network issue, you can also try downgrading AsyncStorage to v1.14.1. That version does not have Room and will not pull in `sqlite-framework`. If you're still seeing it's definitely not AsyncStorage.

I just run ```gradle clean``` after installing older veriosn and re-run the dev but downgrading made no difference, still getting same error.

**Comment by Krizzu** [comment]
@hayyaun so `sqlite-framework` is Flipper's dependency that's missing. I'd try asking in their repo then

**Comment by hayyaun** [comment]
> @hayyaun so `sqlite-framework` is Flipper's dependency that's missing. I'd try asking in their repo then

Thank you, looking for your issue in flipper repo to join.

**Comment by hayyaun** [comment]
Tried removing Flipper completely following this comment, and the problem seems to be disappeared.
[How do I remove Flipper from React Native?](https://github.com/facebook/flipper/issues/1326#issuecomment-653470251)
