### ISSUE TITLE
"Illegal operation" error when reading/writing

### ISSUE THREAD

**Issue by jmrapp1** [react-native-async-storage/async-storage#662]
## Current behavior
When making the following calls with confirmed non-null data:
```
import AsyncStorage from '@react-native-async-storage/async-storage';
...
await AsyncStorage.getItem(key);
...
await AsyncStorage.setItem(key, value);
```
The following exception gets thrown:

```
 1 [BadRequestError: Missing required query parameter=q]
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:720:3)
    at Object.readSync (/Users/jonrapp/Documents/Projects/StockTack/node_modules/graceful-fs/polyfills.js:147:28)
    at tryReadSync (node:fs:430:20)
    at Object.readFileSync (node:fs:476:19)
    at UnableToResolveError.buildCodeFrameMessage (/Users/jonrapp/Documents/Projects/StockTack/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:347:17)
    at new UnableToResolveError (/Users/jonrapp/Documents/Projects/StockTack/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:333:35)
    at ModuleResolver.resolveDependency (/Users/jonrapp/Documents/Projects/StockTack/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:211:15)
    at DependencyGraph.resolveDependency (/Users/jonrapp/Documents/Projects/StockTack/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
    at /Users/jonrapp/Documents/Projects/StockTack/node_modules/@react-native-community/cli/node_modules/metro/src/lib/transformHelpers.js:317:42
    at /Users/jonrapp/Documents/Projects/StockTack/node_modules/@react-native-community/cli/node_modules/metro/src/Server.js:1471:14
```
I've tried multiple different solutions online. Tried clean install, clearing node_modules & reinstalling. Nothing seems to change the output. Cannot find any other information at this point to solve the problem.

## Environment

- **Platforms tested**:
  - [ x ] Android
  - [ ] iOS
  - [ ] macOS
  - [ ] Windows
- **AsyncStorage version**: `^1.15.6`
- **Environment**: 
```
System:
    OS: macOS 10.15.7
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.6.2 - ~/.nvm/versions/node/v16.6.2/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.20.3 - ~/.nvm/versions/node/v16.6.2/bin/npm
    Watchman: 2021.08.02.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 20, 24, 25, 26, 29, 30
      Build Tools: 25.0.0, 25.0.3, 26.0.1, 29.0.2, 30.0.2
      System Images: android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64, android-28 | Google X86_ARM Intel x86 Atom, android-29 | Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_144 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by tido64** [comment]
The stack trace doesn't seem to have anything to do with AsyncStorage or running code for that matter. It looks like this is from a bundle command?

**Comment by jmrapp1** [comment]
I'll take a look in a little while. I'm using react native with metro, running on my android device. I've validated that they're all updated to the newest version. Commenting and uncommenting the lines to read/write with asyncstorage is definitely what is throwing the exception. The outputted stacktrace doesn't seem to be the full output because I don't see it tracing back to my component's call

**Comment by jmrapp1** [comment]
Got back around to this finally. You are correct, the problem had nothing to do with AsyncStorage. Somehow react-native wasn't loving how I was using AsyncStorage along with redux, and was throwing some strange exceptions. With some extra debugging I figured it out. Thanks! Closing.
