### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by Vitor-Vilela** [react-native-async-storage/async-storage#824]
### What happened?

A fatal error occured when starting the App, can't know exactly how or at what point, the error was logged on firebase and it doesn't show much information about it, here are some logs about the crash that happened while doInBackground() was being executed:

Fatal Exception:
```true
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:353)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at com.reactnativecommunity.asyncstorage.SerialExecutor$1.run(SerialExecutor.java:25)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```
       
What caused it:
```true
Caused by java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/br.com.madeiramadeira/databases/RKStorage
       at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
       at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1588)
       at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1464)
       at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1632)
       at com.reactnativecommunity.asyncstorage.AsyncStorageModule$1.doInBackgroundGuarded(AsyncStorageModule.java:132)
       at com.reactnativecommunity.asyncstorage.AsyncStorageModule$1.doInBackgroundGuarded(AsyncStorageModule.java:119)
       at com.facebook.react.bridge.GuardedAsyncTask.doInBackground(GuardedAsyncTask.java:36)
       at com.facebook.react.bridge.GuardedAsyncTask.doInBackground(GuardedAsyncTask.java:20)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at com.reactnativecommunity.asyncstorage.SerialExecutor$1.run(SerialExecutor.java:25)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

Here we have some info about occurrences:
![image](https://user-images.githubusercontent.com/98328435/181040381-fcf283dd-1ede-45e9-8c2a-89a2525188fe.png)

The issue is majorly happening on motorola devices and the logs are from a Samsung Galaxy J5 Prime running on Android 8.0.0

### Version

`@react-native-async-storage/async-storage: 1.16.2` `react-native: 0.67.4`

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 113.06 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.14.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 26, 27, 28, 29, 30, 31, 32
      Build Tools: 29.0.0, 29.0.2, 30.0.2, 30.0.3, 32.1.0
      System Images: android-28 | Google Play Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-30 | Google Play Intel x86 Atom, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4
```

### Steps to Reproduce

Unfortunately I don't have any info on how to reproduce the error, just know it is happening at that function

**Comment by krizzu** [comment]
Hey, seems like this is related to [lifecycle of Activity (Host) being destroyed, where we close db connection.](https://github.com/react-native-async-storage/async-storage/blob/master/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java#L103-L106). The assumption was - if Host is destroyed, then NativeModules are destroyed too, hence `db` close.

I think there's a way to reproduce it, by changing the language on OS or rotating device (which does not kill the activity be default in RN, but might be different in your app). Can you confirm that?

Once you get to reproduce this reliably, you can try enabling [Next storage implementation for Android](https://react-native-async-storage.github.io/async-storage/docs/advanced/next), which does not kill db connection.

Let me know.

**Comment by Vitor-Vilela** [comment]
Unfortunately wasn't able to reproduce the error in any way you mentioned, I will try to apply the Next storage implementation on Android and hope it stops ocurring, anyway, can't bring updates immediately but will try to see the results and update the thread

**Comment by xwartz** [comment]
I have the same issue, but I wasn't able to reproduce it in any way.

**Comment by krizzu** [comment]
This issue seems to be around using an old implementation of AsyncStorage, where we close the DB connection on host destroy. The [next Storage implementation](https://react-native-async-storage.github.io/async-storage/docs/advanced/next) is free from it, so I'd recommend to enable it in project.

**Comment by kai-cupist** [comment]
> Unfortunately wasn't able to reproduce the error in any way you mentioned, I will try to apply the Next storage implementation on Android and hope it stops ocurring, anyway, can't bring updates immediately but will try to see the results and update the thread

Hi there. Were you able to apply the Next storage implementation for Android, and did the issue stop occurring? I'm curious about the results.

**Comment by oa6860289-creator** [comment]
https://github.com/react-native-async-storage/async-storage/issues/824#issuecomment-2421678439
